#!/usr/bin/env python3
"""Cut the UI sprite sheet into pieces and embed them in css/art.css.

The art ships as base64 data URIs inside a CSS file, so the repository holds
no binary files (pull requests here can't carry binaries).

Usage: pip install pillow && python3 tools/build_art.py path/to/ui-sheet.png [--preview]

--preview also writes each piece as a PNG to tools/.preview/ (git-ignored).

Crop boxes are (left, top, right, bottom) in sheet pixels. When new art
arrives, add entries to SPRITES (or a new sheet) and re-run.
"""
import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageDraw

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / 'css' / 'art.css'

# Verb tokens: circle plus the little tab on top. Neighbouring rings touch,
# so each is masked to its own shape.
TOKEN_CX = [130, 366, 603, 839, 1076, 1312]
TOKEN_NAMES = ['duty', 'patrol', 'investigate', 'analyze', 'interrogate', 'reflect']
TOKEN_BOX_Y = (32, 288)
TOKEN_R = 117
TOKEN_CY = 171

SPRITES = {
    # Card frames (label baked into the banner).
    'frame-case': (32, 292, 284, 636),
    'frame-evidence': (316, 292, 576, 636),
    'frame-character': (600, 292, 852, 636),
    'frame-location': (876, 292, 1136, 636),
    'frame-status': (1168, 292, 1420, 636),
    # Clue aspects: icon only, label cropped off.
    'aspect-forensic': (40, 672, 144, 772),
    'aspect-testimony': (162, 672, 262, 772),
    'aspect-motive': (279, 672, 381, 772),
    'aspect-opportunity': (404, 672, 512, 772),
    'aspect-digital': (535, 672, 637, 772),
    'aspect-financial': (656, 672, 768, 772),
    # Status icons: icon only.
    'icon-health': (838, 664, 910, 730),
    'icon-focus': (937, 664, 1007, 730),
    'icon-instinct': (1033, 664, 1107, 730),
    'icon-funds': (1133, 664, 1207, 730),
    'icon-fatigue': (1233, 664, 1307, 730),
    'icon-burnout': (1335, 664, 1413, 730),
    'icon-obsession': (882, 766, 962, 832),
    'icon-pressure': (989, 766, 1067, 832),
    'icon-scrutiny': (1093, 766, 1171, 832),
    'icon-reputation': (1197, 766, 1279, 832),
    'icon-retaliation': (1305, 766, 1383, 832),
    # Misc UI.
    'token-time': (32, 868, 220, 1064),
    'card-back': (232, 820, 416, 1072),
    'divider': (432, 904, 916, 966),
    'icon-alert': (456, 980, 524, 1048),
}

# Longest side, in pixels, for each piece (about 2x its on-screen size).
MAX_SIDE = {'frame': 260, 'aspect': 64, 'icon': 64, 'token': 180, 'card': 200, 'divider': 480, 'alert': 480, 'dialog': 490}


def fit(img, name):
    limit = next((v for k, v in MAX_SIDE.items() if name.startswith(k)), 256)
    scale = min(1.0, limit / max(img.size))
    if scale < 1:
        img = img.resize((round(img.width * scale), round(img.height * scale)), Image.LANCZOS)
    return img


def encode(img):
    buf = io.BytesIO()
    img.save(buf, 'WEBP', quality=82, method=6)
    return 'data:image/webp;base64,' + base64.b64encode(buf.getvalue()).decode('ascii')


def tokens(sheet):
    out = {}
    y0, y1 = TOKEN_BOX_Y
    for cx, name in zip(TOKEN_CX, TOKEN_NAMES):
        box = (cx - TOKEN_R - 2, y0, cx + TOKEN_R + 2, y1)
        crop = sheet.crop(box)
        mask = Image.new('L', crop.size, 0)
        d = ImageDraw.Draw(mask)
        ox = box[0]
        d.ellipse((cx - TOKEN_R - ox, TOKEN_CY - TOKEN_R - y0, cx + TOKEN_R - ox, TOKEN_CY + TOKEN_R - y0), fill=255)
        d.rounded_rectangle((cx - 58 - ox, 0, cx + 58 - ox, 60), radius=12, fill=255)
        alpha = Image.composite(crop.getchannel('A'), mask, mask)
        crop.putalpha(alpha)
        out['token-' + name] = crop
    return out


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    sheet = Image.open(sys.argv[1]).convert('RGBA')
    pieces = tokens(sheet)
    for name, box in SPRITES.items():
        pieces[name] = sheet.crop(box)
    lines = ['/* Generated by tools/build_art.py. Do not edit by hand. */', ':root {']
    total = 0
    for name, img in pieces.items():
        uri = encode(fit(img, name))
        total += len(uri)
        lines.append('  --art-%s: url("%s");' % (name, uri))
    lines.append('}')
    OUT.write_text('\n'.join(lines) + '\n')
    if '--preview' in sys.argv:
        prev = ROOT / 'tools' / '.preview'
        prev.mkdir(exist_ok=True)
        for name, img in pieces.items():
            img.save(prev / (name + '.png'))
    print('wrote %s: %d pieces, %.0f KB' % (OUT.relative_to(ROOT), len(pieces), total / 1024))


if __name__ == '__main__':
    main()
