#!/usr/bin/env python3
"""Cut the second batch of sheets (the kit: bodies, seals, court, links, tags)
into css/art/kit-*.css as base64 WebP custom properties --art-<key>.

Usage:
    python3 tools/build_kit_art.py path/to/sheets/ [--preview]

The folder holds the sheets as k01.png ... k16.png in the order they were
supplied (docs/ART.md lists which is which). Tiles are found by their
non-background pixels, row by row, so the sheets need no hand-measured boxes;
the sheets whose tiles touch are cut on an even grid instead.
"""
import os, sys, json
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_noir_art import encode, montage, ROOT, OUT
from PIL import Image
import numpy as np

FILES = {
    'kit-cards': dict(width=200, q=66),   # pictures for card faces
    'kit-icons': dict(width=96, q=76),    # seals, chips, tags, pins
}

def runs(v, gap):
    out, start = [], None
    for i, x in enumerate(v):
        if x and start is None: start = i
        if not x and start is not None:
            if i - start > 2: out.append([start, i])
            start = None
    if start is not None: out.append([start, len(v)])
    m = []
    for r in out:
        if m and r[0] - m[-1][1] <= gap: m[-1][1] = r[1]
        else: m.append(r)
    return m

def detect(im):
    """Tile boxes, reading order, from everything that is not the background."""
    a = np.asarray(im.convert('RGB')).astype(int)
    bg = np.median(a[:8, :8].reshape(-1, 3), axis=0)
    mask = np.abs(a - bg).sum(axis=2) > 70
    boxes = []
    for y0, y1 in runs(mask.any(axis=1), 10):
        if y1 - y0 < 60: continue
        band = mask[y0:y1]
        for x0, x1 in runs(band.any(axis=0), 10):
            if x1 - x0 < 60: continue
            ys = np.where(band[:, x0:x1].any(axis=1))[0]
            boxes.append((x0, y0 + ys[0], x1, y0 + ys[-1] + 1))
    # Two tiles that touch come out as one wide box: split it by the usual width.
    widths = sorted(b[2] - b[0] for b in boxes)
    med = widths[len(widths) // 2]
    out = []
    for b in boxes:
        n = max(1, round((b[2] - b[0]) / med))
        pw = (b[2] - b[0]) / n
        for i in range(n): out.append((round(b[0] + i * pw), b[1], round(b[0] + (i + 1) * pw), b[3]))
    return out

def grid(box, cols, rows, pad=0.02):
    x0, y0, x1, y1 = box
    pw, ph = (x1 - x0) / cols, (y1 - y0) / rows
    return [(round(x0 + c * pw + pw * pad), round(y0 + r * ph + ph * pad), round(x0 + (c + 1) * pw - pw * pad), round(y0 + (r + 1) * ph - ph * pad))
            for r in range(rows) for c in range(cols)]

# sheet -> (file, [(prefix, how)]) where how is 'detect' or (cols, rows) or (cols, rows, row-index) for one row
SHEETS = {
    'k01': ('kit-cards', [('kdeath', 'detect')]),
    'k02': ('kit-cards', [('kstab', 'detect')]),
    'k03': ('kit-cards', [('kblunt', 'detect')]),
    'k04': ('kit-cards', [('khang', 'detect')]),
    'k05': ('kit-cards', [('kpoison', 'detect')]),
    'k06': ('kit-cards', [('kdrown', 'detect')]),
    'k07': ('kit-cards', [('kbody', 'detect')]),
    'k08': ('kit-cards', [('kshot', 'detect')]),
    'k09': ('kit-icons', [('kseal', (6, 5))]),
    'k10': ('kit-cards', [('kfolk', (6, 5))]),
    'k11': ('kit-icons', [('knum', (7, 7, 0)), ('knext', (7, 7, 1)), ('ktag', (7, 7, 2)), ('klink', (7, 7, 3)), ('krope', (7, 7, 4)), ('kwax', (7, 7, 5)), ('kplate', (7, 7, 6))]),
    'k12': ('kit-cards', [('kcourt', (6, 5))]),
    'k13': ('kit-icons', [('karrow', (6, 5, 0)), ('krel', (6, 5, 1)), ('kpin', (6, 5, 2)), ('ktime', (6, 5, 3)), ('kplace', (6, 5, 4))]),
    'k14': ('kit-cards', [('kinv', 'detect')]),
    'k15': ('kit-cards', [('kev', 'detect')]),
    'k16': ('kit-icons', [('kros', (8, 4, 0)), ('kros2', (8, 4, 1)), ('kbadge', (8, 4, 2)), ('klabel', (8, 4, 3))]),
}

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if not args: sys.exit(__doc__)
    folder, preview = args[0], '--preview' in sys.argv
    pv = os.path.join(ROOT, 'tools', '.preview', 'kit')
    if preview: os.makedirs(pv, exist_ok=True)
    lines = {f: ['/* Generated by tools/build_kit_art.py from the kit sheets. Do not edit. */', ':root {'] for f in FILES}
    fams = {f: {} for f in FILES}
    total = 0
    for sname, (file, families) in SHEETS.items():
        p = os.path.join(folder, sname + '.png')
        if not os.path.exists(p): print('missing', p); continue
        im = Image.open(p).convert('RGBA')
        found = detect(im)
        ux0, uy0 = min(b[0] for b in found), min(b[1] for b in found)
        ux1, uy1 = max(b[2] for b in found), max(b[3] for b in found)
        for prefix, how in families:
            if how == 'detect': boxes = found
            elif len(how) == 2: boxes = grid((ux0, uy0, ux1, uy1), how[0], how[1])
            else:
                cols, rows, r = how
                boxes = grid((ux0, uy0, ux1, uy1), cols, rows)[r * cols:(r + 1) * cols]
            for i, box in enumerate(boxes):
                key = '%s-%02d' % (prefix, i + 1)
                if file == 'kit-cards':
                    w, h = box[2] - box[0], box[3] - box[1]
                    box = (round(box[0] + 0.07 * w), round(box[1] + 0.07 * h), round(box[2] - 0.07 * w), round(box[3] - 0.07 * h))
                piece = im.crop(box)
                if piece.getextrema()[3][0] == 255: piece = piece.convert('RGB')
                uri, small = encode(piece, FILES[file]['width'], FILES[file]['q'])
                lines[file].append('  --art-%s: url("%s");' % (key, uri))
                total += len(uri)
                fams[file].setdefault(prefix, []).append((key, small))
    for file in FILES:
        lines[file].append('}')
        with open(os.path.join(OUT, file + '.css'), 'w') as f: f.write('\n'.join(lines[file]) + '\n')
        n = sum(len(v) for v in fams[file].values())
        print('%s: %d pieces (%s)' % (file, n, ', '.join('%s %d' % (k, len(v)) for k, v in fams[file].items())))
        if preview:
            for fam, ps in fams[file].items(): montage(ps, os.path.join(pv, fam + '.png'))
    print('total %.1f MB of data URIs' % (total / 1e6))

if __name__ == '__main__':
    main()
