#!/usr/bin/env python3
"""Cut the third batch of sheets (the deck: portraits, roles, items, places,
verb tiles, buttons, tokens, seals, the study) into css/art/deck-*.css as
base64 WebP custom properties --art-<key>.

Usage:
    python3 tools/build_deck_art.py path/to/sheets/ [--preview]

The folder holds the sheets as d01.png ... d16.png in the order they were
supplied (docs/ART.md lists which is which). Tiles are found by their pixels
(tools/build_kit_art.py's detector); a family takes a slice of the tiles
found, and may keep only part of each tile (the picture above a word band).
"""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from build_noir_art import encode, montage, ROOT, OUT
from PIL import Image
import numpy as np

def runs(v, gap, least):
    out, start = [], None
    for i, x in enumerate(list(v) + [False]):
        if x and start is None: start = i
        if not x and start is not None:
            if i - start >= least: out.append([start, i])
            start = None
    m = []
    for r in out:
        if m and r[0] - m[-1][1] <= gap: m[-1][1] = r[1]
        else: m.append(r)
    return m

def rows_of(im, gap=4, least=40):
    """Tiles as rows of boxes: transparent sheets by their alpha, opaque ones
    by their distance from the corner colour. Small things (labels) are dropped."""
    a = np.asarray(im.convert('RGBA')).astype(int)
    if a[:, :, 3].min() < 250: mask = a[:, :, 3] > 40
    else:
        bg = np.median(a[:8, :8, :3].reshape(-1, 3), axis=0)
        mask = np.abs(a[:, :, :3] - bg).sum(axis=2) > 70
    rows = []
    for y0, y1 in runs(mask.any(axis=1), gap, least):
        band = mask[y0:y1]
        row = []
        for x0, x1 in runs(band.any(axis=0), gap, least):
            ys = np.where(band[:, x0:x1].any(axis=1))[0]
            row.append((x0, y0 + ys[0], x1, y0 + ys[-1] + 1))
        rows.append(row)
    return rows

FILES = {
    'deck-cards': dict(width=200, q=66),   # pictures for card faces
    'deck-icons': dict(width=128, q=76),   # buttons, tokens, seals, flags
    'deck-menu': dict(width=1400, q=58),   # the study behind the menus
}

# sheet -> (file, [(prefix, row, start, count, crop)]): the tiles of one row
# (None: every row, reading order), a slice of them, and the part of each tile
# to keep as fractions (x0, y0, x1, y1), None for the whole tile.
PIC = (0.06, 0.26, 0.94, 0.68)   # an item card: the picture above its band, below the blank badge
S = {
    'd01': ('deck-cards', [('dport', None, 0, 35, (0.04, 0.04, 0.96, 0.96))]),
    'd02': ('deck-icons', [('dicon', None, 0, 26, None)]),
    'd03': ('deck-icons', [('dui', None, ('grid', 5, 5), 25, (0.02, 0.02, 0.98, 0.98))]),
    'd08': ('deck-cards', [('dverb', None, 0, 16, ('sq', 0.5, 0.37, 0.33))]),   # the circle, square, without the word band
    'd09': ('deck-icons', [('dtok', 1, 0, 8, None)]),
    'd10': ('deck-icons', [('dwax', 3, ('grid', 8, 2), 16, (0.03, 0.03, 0.97, 0.97)), ('dflag', 4, 6, 6, None)]),
    'd11': ('deck-cards', [('ditem', None, 0, 12, PIC)]),
    'd12': ('deck-cards', [('drole', None, 0, 12, (0.03, 0.03, 0.97, 0.97))]),
    'd14': ('deck-icons', [('dbtn', 1, 0, 11, None), ('dbtn2', 2, 0, 11, None), ('dbtn3', 3, 0, 7, None)]),
    'd15': ('deck-cards', [('dhero', None, 0, 8, (0.04, 0.20, 0.96, 0.74))]),
    'd16': ('deck-cards', [('dloc', None, 0, 10, (0.04, 0.03, 0.96, 0.50))]),
}

def main():
    args = [a for a in sys.argv[1:] if not a.startswith('--')]
    if not args: sys.exit(__doc__)
    folder, preview = args[0], '--preview' in sys.argv
    pv = os.path.join(ROOT, 'tools', '.preview', 'deck')
    if preview: os.makedirs(pv, exist_ok=True)
    lines = {f: ['/* Generated by tools/build_deck_art.py from the deck sheets. Do not edit. */', ':root {'] for f in FILES}
    fams = {f: {} for f in FILES}
    total = 0
    def put(file, key, piece):
        nonlocal total
        if piece.mode == 'RGBA' and piece.getextrema()[3][0] == 255: piece = piece.convert('RGB')
        uri, small = encode(piece, FILES[file]['width'], FILES[file]['q'])
        lines[file].append('  --art-%s: url("%s");' % (key, uri))
        total += len(uri)
        fams[file].setdefault(key.split('-')[0], []).append((key, small))
    # The study: one picture, whole.
    p = os.path.join(folder, 'd04.png')
    if os.path.exists(p): put('deck-menu', 'dmenu', Image.open(p).convert('RGB'))
    for sname, (file, families) in S.items():
        p = os.path.join(folder, sname + '.png')
        if not os.path.exists(p): print('missing', p); continue
        im = Image.open(p).convert('RGBA')
        rows = rows_of(im)
        print(sname, 'rows:', [len(r) for r in rows])
        for prefix, row, start, count, crop in families:
            found = [b for r in rows for b in r] if row is None else rows[row]
            if isinstance(start, tuple):
                # An even grid over everything found: tiles that touch.
                _, cols, nrows = start
                ux0, uy0 = min(b[0] for b in found), min(b[1] for b in found)
                ux1, uy1 = max(b[2] for b in found), max(b[3] for b in found)
                pw, ph = (ux1 - ux0) / cols, (uy1 - uy0) / nrows
                found = [(round(ux0 + c * pw), round(uy0 + r * ph), round(ux0 + (c + 1) * pw), round(uy0 + (r + 1) * ph)) for r in range(nrows) for c in range(cols)]
                start = 0
            boxes = found[start:start + count]
            if len(boxes) < count: print('%s: %s wants %d tiles from %d, found %d' % (sname, prefix, count, start, len(found)))
            for i, box in enumerate(boxes):
                if crop and crop[0] == 'sq':
                    # A square about a point: (cx, cy) as fractions, half-size as a fraction of the width.
                    w, h = box[2] - box[0], box[3] - box[1]
                    cx, cy, r = box[0] + crop[1] * w, box[1] + crop[2] * h, crop[3] * w
                    box = (round(cx - r), round(cy - r), round(cx + r), round(cy + r))
                elif crop:
                    w, h = box[2] - box[0], box[3] - box[1]
                    box = (round(box[0] + crop[0] * w), round(box[1] + crop[1] * h), round(box[0] + crop[2] * w), round(box[1] + crop[3] * h))
                put(file, '%s-%02d' % (prefix, i + 1), im.crop(box))
    for file in FILES:
        lines[file].append('}')
        with open(os.path.join(OUT, file + '.css'), 'w') as f: f.write('\n'.join(lines[file]) + '\n')
        n = sum(len(v) for v in fams[file].values())
        print('%s: %d pieces (%s)' % (file, n, ', '.join('%s %d' % (k, len(v)) for k, v in fams[file].items())))
        if preview:
            for fam, ps in fams[file].items(): montage(ps, os.path.join(pv, fam + '.png'))
    print('total %.1f MB of data URIs' % (total / 1e6))

if __name__ == '__main__':
    main()
